function srk9_help --description "Display SRK9 help and available commands"
    echo "SRK9 System Redundancy Manager - Help"
    echo "======================================"
    echo ""
    echo "Available commands:"
    echo "  srk9_init              - Initialize SRK9 system"
    echo "  srk9_backup            - Backup current dotfiles"
    echo "  srk9_install_bun       - Install Bun runtime locally"
    echo "  srk9_install_homebrew  - Install Homebrew locally"
    echo "  srk9_install_volta     - Install Volta Node.js manager"
    echo "  srk9_install_claude    - Install Claude CLI"
    echo "  srk9_manage_dotfiles   - Manage dotfiles with symlinks"
    echo "  srk9_cleanup           - Clean up system files"
    echo "  srk9_reset             - Reset development environment"
    echo "  srk9_update            - Update SRK9 system"
    echo ""
    echo "Configuration:"
    echo "  srk9_symlink_dots      - Create symlinks for dotfiles"
    echo "  srk9_cleanup_dots      - Clean up dotfile symlinks"
    echo ""
    echo "For more information about a specific command, use: help <command_name>"
end