function srk9-help --description "Show srk9 help and available commands"
    echo "SrK9 - Systems Redundancy & Recovery Agent"
    echo "========================================================"
    echo ""
    echo "INSTALLATION COMMANDS:"
    echo "  srk9-install-bun          Install Bun runtime locally"
    echo "  srk9-install-homebrew     Install Homebrew globally"
    echo "  srk9-install-volta        Install Volta Node.js manager"
    echo "  srk9-install-rosetta      Install Rosetta (Apple Silicon)"
    echo "  srk9-install-claude       Install Claude CLI"
    echo "  srk9-install-rust         Install Rust via rustup"
    echo "  srk9-install-python       Install Python via pyenv"
    echo "  srk9-install-go           Install Go programming language"
    echo "  srk9-install-docker       Install Docker"
    echo ""
    echo "UNINSTALL COMMANDS:"
    echo "  srk9-uninstall-bun        Remove Bun installation"
    echo "  srk9-uninstall-volta      Remove Volta installation"
    echo "  srk9-uninstall-rust       Remove Rust installation"
    echo "  srk9-uninstall-python     Remove pyenv installation"
    echo "  srk9-uninstall-go         Remove Go installation"
    echo ""
    echo "STATUS & UTILITIES:"
    echo "  srk9-status               Show status of installed tools"
    echo "  srk9-list-functions       List all srk9 functions"
    echo "  srk9-backup-dots          Backup dotfiles with timestamp"
    echo "  srk9-restore-dots         Restore dotfiles from backup"
    echo "  srk9-help                 Show this help message"
    echo ""
    echo "DOTFILES MANAGEMENT:"
    echo "  srk9-dots-init            Initialize dotfiles management"
    echo "  srk9-dots-link            Create symlinks for dotfiles"
    echo "  srk9-dots-status          Show dotfiles sync status"
    echo ""
    echo "========================================================"
    echo "For more information, visit: https://github.com/srk9/bootstrapper"
end
